### ISSUE TITLE
Clone current Prisma docs into this repo and apply Nexus branding

### ISSUE THREAD

**Issue by nikolasburk** [graphql-nexus/docs#1]
https://www.notion.so/prismaio/Nexus-docs-3cabeac4b62d462cb93306186722bd08#e7f1ab24988d4d39a962c10ade40092c

**Comment by jasonkuhrt** [comment]
How will the new site deal with this kind of doc layout ([link](https://www.nexusjs.org/#/plugins/prisma?id=example-7)):

![image](https://user-images.githubusercontent.com/284476/80392004-8eb88100-887c-11ea-8f21-13d2304266d8.png)

**Comment by nikolasburk** [comment]
So, Nilu will be building an MDX component that allows to have code blocks side-by-side, more info here: https://www.notion.so/prismaio/Docs-MDX-Code-block-9af4545b78c6455aa70f2e596a639905

I think a general problem there might be though that afaik the docs layout has a fixed width, so that might result in really cramped code blocks if they're all side-by-side...

**Comment by jasonkuhrt** [comment]
> docs layout has a fixed width

I guess we could customize with the necessary css to add responsiveness stuff until a "proper" core solution is designed?

Is there any eng/prod issue tracking in place that we can discuss enhancements like this? Don't want to fragment communication, add more overhead, etc. 🙏
