### ISSUE TITLE
docs or website?

### ISSUE THREAD

**Issue by jasonkuhrt** [graphql-nexus/docs#2]
This repo is called docs but our current plan is to keep docs co-located with code so that we can ship code+docs in the same PR.

So what will be in this repo exactly?

I'm currently thinking it should be called website instead.

**Comment by janpio** [comment]
We can easily rename this to `website` when we want - I agree that this is a misnomer right now.

**Comment by jasonkuhrt** [comment]
Based on more recent discussions, my current understanding is that this repo would go away as colocated docs would imply colocated website.
